version: '2.1'

volumes:
    plant-data:

services:
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80"
    volumes:
      - 'plant-data:/data'
    environment:
        - 'GF_SERVER_HTTP_PORT=80'
        - 'GF_PATHS_PROVISIONING=/usr/src/app/provisioning'
        - 'GF_SESSION_PROVIDER=memory'
    depends_on:
      - influxdb
  influxdb:
    restart: always
    build: ./influxdb
    volumes:
      - 'plant-data:/data'
  plantsaver:
    build: ./plantsaver
    privileged: true
    restart: always
    labels:
      io.balena.features.balena-api: '1'
